name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Java kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Firebase yapılandırma dosyasını ayarla
        run: echo "${{ secrets.FIREBASE_CONFIG }}" > ./src/main/resources/firebase-config.json

      - name: Gradle dosyasına çalıştırma izni ver
        run: chmod +x ./gradlew

      - name: Gradle ile build
        run: ./gradlew clean build -x test
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./src/main/resources/firebase-config.json