name: Firebase CD (Hosting + Firestore + Cloud Run)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Node.js kur
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Java kur
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Firebase CLI yükle
        run: npm install -g firebase-tools

      - name: gcloud CLI kurulumu
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cai-socialmedia
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Frontend bağımlılıklarını kur ve build et
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Firebase deploy (Hosting + Firestore)
        run: firebase deploy --only hosting,firestore --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Backend'i Cloud Run ile deploy et
        run: |
          gcloud builds submit --tag gcr.io/cai-socialmedia/socialmedia-backend
          gcloud run deploy socialmedia-backend \
            --image gcr.io/cai-socialmedia/socialmedia-backend \
            --platform managed \
            --region europe-west4 \
            --allow-unauthenticated \
            --port 8080